tolerance: 1e-3
max_iterations: 5
omega: 1
coupling_scheme: "serial-implicit"

K: 1.0
c: 1.0
L: 1.0
h_0: 1.0
t_0: 0
t_end: 0.1

N: 1
M: 20

bc_type: dirichlet
dirichlet_value: 0.0
ic_type: linear

precice_config_template: "coupling/precice-config.xml.j2"
precice_config: "coupling/precice-config.xml"